### ISSUE TITLE
Feature Request: Support lists of dicts 

### ISSUE THREAD

**Issue by RobinU434** [RobinU434/Config2Class#5]
Support this as List of dataclass objects in code. 

```yaml
block_config:
    - in_channels: 64
      out_channels: 128
      channels: [64]
    - in_channels: 128
      out_channels: 256
      channels: [128]
    - in_channels: 256
      out_channels: 512
      channels: [256]
```
